// <auto-generated />
namespace lab3_.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updateDocHosRelation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateDocHosRelation));
        
        string IMigrationMetadata.Id
        {
            get { return "202405232316498_updateDocHosRelation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
